//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.QualityControl
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T тип устройства.
    /// </summary>
    // *** Start programmer edit section *** (tТипУстройства CustomAttributes)

    // *** End programmer edit section *** (tТипУстройства CustomAttributes)
    public enum tТипУстройства
    {
        
        // *** Start programmer edit section *** (tТипУстройства.Поляризирующее CustomAttributes)

        // *** End programmer edit section *** (tТипУстройства.Поляризирующее CustomAttributes)
        Поляризирующее,
        
        // *** Start programmer edit section *** (tТипУстройства.Герметизирующее CustomAttributes)

        // *** End programmer edit section *** (tТипУстройства.Герметизирующее CustomAttributes)
        Герметизирующее,
    }
}
